module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.imgurl = [
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421917/SeedPics/aniket-deole-T-tOgjWZ0fQ-unsplash_1_ag4dbj.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421916/SeedPics/adrian-infernus-fTKkJL5Xjw8-unsplash_aikbbv.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421915/SeedPics/jon-flobrant-JU2MgHOHDsw-unsplash_ujregj.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421914/SeedPics/greg-shield-GA3NfIOHkUg-unsplash_pxqouy.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421912/SeedPics/aniket-deole-T-tOgjWZ0fQ-unsplash_tsjdes.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421911/SeedPics/ali-gooya-3yIBNntfdXU-unsplash_zm7ls7.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421907/SeedPics/stefan-kunze-1-C334jLxG0-unsplash_prrzqa.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421904/SeedPics/artem-beliaikin-XF9Zz6xlNJg-unsplash_esco29.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421901/SeedPics/alec-douglas-LfPPlfCWjjw-unsplash_arpn0w.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421900/SeedPics/zoltan-tasi-wqIq3b9Xclo-unsplash_wo2upu.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421899/SeedPics/james-donovan-YIgNXfXwYFU-unsplash_x0ceha.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421896/SeedPics/pars-sahin-mjQpWnLzKD0-unsplash_mvlhg8.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421895/SeedPics/eleonore-kemmel-8mY3XGmmTUo-unsplash_igulfp.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421893/SeedPics/cyrill-hanni-sPXGnvwOjdU-unsplash_zq7qe3.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421893/SeedPics/jacek-dylag-a3Vz5qEbbWI-unsplash_syl0kr.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421891/SeedPics/balazs-busznyak-98XygxjkWV4-unsplash_mnha6w.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421891/SeedPics/casey-horner-pQvARUrZQ1g-unsplash_a845uh.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421888/SeedPics/tabitha-turner-N5dj-ypoQpI-unsplash_mllggr.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421887/SeedPics/joel-jasmin-forestbird-iNPs5ftmyj0-unsplash_kkvi2p.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421886/SeedPics/taylor-murphy-zFjnuaEcfFw-unsplash_gsqpra.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421886/SeedPics/lukas-tennie-54Pfu4EK4pc-unsplash_sjvp61.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421884/SeedPics/faye-cornish-n3XTxxV7qhI-unsplash_tqtl42.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421883/SeedPics/echo-grid-UeeIRVCO_28-unsplash_woidjp.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421882/SeedPics/debbie-frith-6SQBR77lexo-unsplash_vqeusw.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421880/SeedPics/ashley-jurius-vCTzJZuyTLo-unsplash_li8b08.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421880/SeedPics/luke-flynt-S0pBkD1t7UQ-unsplash_q1iwpe.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421880/SeedPics/ameen-fahmy-7RZj4IrPT9Y-unsplash_rfwb3q.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421880/SeedPics/paxson-woelber-1yOkW4UwYbA-unsplash_ox65de.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421879/SeedPics/tomas-malik-bMmvCJJsAh8-unsplash_o4oeo4.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421878/SeedPics/christine-mendoza-9gOV9Jz6Gho-unsplash_wxev7u.jpg',
	'https://res.cloudinary.com/de0p7fzif/image/upload/v1641421904/SeedPics/artem-beliaikin-XF9Zz6xlNJg-unsplash_esco29.jpg',
];

module.exports.imgfilename = [
	'aniket-deole-T-tOgjWZ0fQ-unsplash_1_ag4dbj',
	'adrian-infernus-fTKkJL5Xjw8-unsplash_aikbbv',
	'jon-flobrant-JU2MgHOHDsw-unsplash_ujregj',
	'greg-shield-GA3NfIOHkUg-unsplash_pxqouy',
	'aniket-deole-T-tOgjWZ0fQ-unsplash_tsjdes',
	'ali-gooya-3yIBNntfdXU-unsplash_zm7ls7',
	'stefan-kunze-1-C334jLxG0-unsplash_prrzqa',
	'artem-beliaikin-XF9Zz6xlNJg-unsplash_esco29',
	'alec-douglas-LfPPlfCWjjw-unsplash_arpn0w',
	'zoltan-tasi-wqIq3b9Xclo-unsplash_wo2upu',
	'james-donovan-YIgNXfXwYFU-unsplash_x0ceha',
	'pars-sahin-mjQpWnLzKD0-unsplash_mvlhg8',
	'eleonore-kemmel-8mY3XGmmTUo-unsplash_igulfp',
	'cyrill-hanni-sPXGnvwOjdU-unsplash_zq7qe3',
	'jacek-dylag-a3Vz5qEbbWI-unsplash_syl0kr',
	'balazs-busznyak-98XygxjkWV4-unsplash_mnha6w',
	'casey-horner-pQvARUrZQ1g-unsplash_a845uh',
	'tabitha-turner-N5dj-ypoQpI-unsplash_mllggr',
	'joel-jasmin-forestbird-iNPs5ftmyj0-unsplash_kkvi2p',
	'taylor-murphy-zFjnuaEcfFw-unsplash_gsqpra',
	'lukas-tennie-54Pfu4EK4pc-unsplash_sjvp61',
	'faye-cornish-n3XTxxV7qhI-unsplash_tqtl42',
	'echo-grid-UeeIRVCO_28-unsplash_woidjp',
	'debbie-frith-6SQBR77lexo-unsplash_vqeusw',
	'ashley-jurius-vCTzJZuyTLo-unsplash_li8b08',
	'luke-flynt-S0pBkD1t7UQ-unsplash_q1iwpe',
	'ameen-fahmy-7RZj4IrPT9Y-unsplash_rfwb3q',
	'paxson-woelber-1yOkW4UwYbA-unsplash_ox65de',
	'tomas-malik-bMmvCJJsAh8-unsplash_o4oeo4',
	'christine-mendoza-9gOV9Jz6Gho-unsplash_wxev7u',
	'artem-beliaikin-XF9Zz6xlNJg-unsplash_esco29',
];